services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: adonis_learn
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080

  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
